import { ReactElement } from 'react';
import { I18nProviderServer } from '../../locales/server';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactElement;
  params: { locale: string };
}) {
  return (
    <html lang="en">
      <body>
        <I18nProviderServer locale={locale}>{children}</I18nProviderServer>
      </body>
    </html>
  );
}
