import { I18nContext } from '@/locales/server';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang="en">
      <body>
        <I18nContext locale={locale}>{children}</I18nContext>
      </body>
    </html>
  );
}
