name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Run ESLint
      run: pnpm lint
  typecheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build next-international
      run: cd packages/next-international && pnpm build
    - name: Run TSC
      run: pnpm typecheck
